version: '2.1'

services:
  httpd:
    build:
      dockerfile: ./apache_php8_1_6/Dockerfile
      context: ./
    volumes:
      - ./docroot:/var/www/html
    ports:
      - "18080:80"
    restart: always
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "13306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
  redis:
    image: "redis:latest"
    ports:
      - "16379:6379"
    restart: always
